### ISSUE TITLE
Develop a MVP for Token Vesting with lockup_linear functionality

### ISSUE THREAD

**Issue by Akashneelesh** [starknet-io/tokei#14]
### 🔍 Project Overview
Transitioning a token vesting smart contract from Solidity to Cairo. The original contract in Solidity manages token vesting with a lockup_linear feature. Goal: replicate and optimize this functionality in Cairo.

### 🎯 Objectives
1. **Replicate Core Features:** Maintain all essential functionalities from the Solidity version.
2. **Cairo Optimization:** Adapt and optimize for Cairo language features.
3. **Maintain Security Standards:** High security and robustness in the Cairo implementation.

### 🔑 Key Features
- **Lockup Linear Streams:** Implement stream mapping, creation, and management.
- **User-Facing Functions:** Port functions like `getAsset`, `getCliffTime`, etc., to Cairo.
- **Internal Logic:** Replicate internal logic such as `_calculateStreamedAmount`, `_statusOf`, etc.
- **Error Handling:** Adapt custom error handling.

### 🧪 Testing and Validation
- Develop comprehensive unit and integration tests.
- Adapt and mirror test cases from Solidity to Cairo.
- Working examples usage with Starknet.js for example

### 📚 Documentation
- Detailed code comments for clarity.
- Documentation comparing Solidity and Cairo versions.
- Usage instructions and examples.

**Comment by Akashneelesh** [comment]
> Approved scope, ready for work. Assigned to you. Grant: 10k STRK (paid through Only Dust upon completion and validation of the MVP).

Thank you !

**Comment by AbdelStark** [comment]
Validated and paid.
